#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod i_swap_router;
pub mod i_uniswap_v2_factory;
pub mod i_uniswap_v2_pair;
pub mod i_uniswap_v2_router_02;
pub mod i_uniswap_v3_factory;
pub mod i_uniswap_v3_pool;
pub mod i_universal_router;
pub mod i_universal_router_commands;
pub mod ierc20;
pub mod iweth;
